### PR TITLE
fix for updating connection status

### PR DESCRIPTION
**Pull request by knippers**
Hi Michel,

thanks for creating this app. I had just started basically creating the same app. Just when I had the project outline almost ready I noticed the app in the app store. Saves me to do the coding (not a native nodejs coder so things take a bit longer then). 

I noticed the app connection status under settings is not updated after changing settings. When you move away from the app settings and back to it status is reflected correctly. 

This patch is how I fixed it. Obviously feel free to reject the pull and implement it in your own way.

I will start playing around with the app for some days and should I find something I will try to debug and fix the code.

Btw, I run controller 5.5.1.

### CODE REVIEW

**Comment by mnederlof** [comment]
Hi, thanks for trying to debug my work :smile:

Don't really see though how this is actually different in regard to how it was before your pull request?

**Comment by knippers** [comment]
The difference is the times the status field is updated. Once at "opening" of the settings page. Once just after clicking the save button and once in the timeout.

Before it would reflect the correct connection status only at initial settings page view. 

Daniel

**Comment by mnederlof** [comment]
Ah, now i see that :)

The thing is, it should listen for realtime events sent from the app. That is where this line of code is for:
```
            Homey.on('com.ubnt.unifi.status', ( data ) => { updateStatusField(null, data); });
```

So that way i don't need a setTimeout or something to update my status value.

If (for some reason) the settings are not filled in, and the status is not displayed, then it probably means that the app crashed.. :( (i fixed that btw in the next version).

Can you let me know if the next release (0.0.2) has fixed the issue you had an tried to fix with this code?

**Comment by knippers** [comment]
Tried the latest code but no success. No status update and no live debug messages. I then tried again via a regular browser (ignoring the not supported message) and success (both status and debug messages). Will have to read into how the settings pages are dealt with in the desktop app (Mac OS X and Windows).

**Comment by knippers** [comment]
closing the pull request, it is no longer valid.

**Comment by mnederlof** [comment]
Oh, nice catch, i have not used the desktop app, so only used the browser... i'll create an issue for it to keep track of it, when i have the time to debug that issue.

**Pull request closed without merging**
