### PR TITLE
Version 2.0.4 added icons to custom capabilities

### PR DESCRIPTION
**Pull request by rhannink**
Hello,

I have made some very minor changes to display the icons for your custom capabilities again.
I have tested this commit on Homey 2.0.0 firmware.

### CODE REVIEW

**Comment by mnederlof** [comment]
Thanks for this help, could you please make the diff smaller, as all indentation is redone and that is not really needed (and gives wrong impression of the change)

**Comment by rhannink** [comment]
I did a fork and edited just a few lines with vi. Not sure while all the idents changed...
Any tips on how to overcome this ?

**Comment by mnederlof** [comment]
Maybe

> I did a fork and edited just a few lines with vi. Not sure while all the idents changed...
> Any tips on how to overcome this ?

Probably you have some plugins enabled in vi, that is doing automatic re-alignment. So use another editor or checkout what is causing it in vi :)

**Comment by rhannink** [comment]
Now looks better, used Atom instead of vi.......Could you please check if everything is ok now...

**Comment by mnederlof** [comment]
Yes, better, thanks!

**Pull request merged**
