### PR TITLE
Add ability to also act on non-paired connecting/disconnecting clients, add SSID, guest and group tags to relevant Flow actions

### PR DESCRIPTION
**Pull request by arpiecodes**

### CODE REVIEW

**Comment by mnederlof** [comment]
@synegic , why do you want to monitor non-paired clients?

**Comment by arpiecodes** [comment]
Because I prefer to use UniFi Manager for my user/usergroup management. Also, this way I can react on devices joining my guest network (and react on this accordingly in flows).

Right now, my use case with my edits is just that (monitoring guests), but also checking of someone from my family is near (disable alarm) or friends are near. These commits allow me to act on these events without adding those devices manually as devices.

I mean, the data is fetched and pulled anyways, so why not use it. :-)

**Comment by mnederlof** [comment]
That is true, i'll incorporate it in the SDKv2 rewrite i'm working on. Thanks for the idea!

**Comment by mnederlof** [comment]
sdkv2 is default branch now, and there is already incorporated.

**Pull request closed without merging**
